import { useEffect } from 'react';
import { LegalDocument, type LegalSection, legalLinkStyle } from '../components/legal/LegalDocument';

const META_DESCRIPTION = 'Read the Vibe Station Shipping Policy for processing times, dispatch, delivery, and shipment support details.';

const sections: LegalSection[] = [
  {
    title: '1. Order Processing',
    blocks: [
      {
        type: 'paragraph',
        content:
          'Orders are usually processed within 1 to 3 business days unless a different timeline is shown on the product page, at checkout, or in a specific announcement.'
      },
      { type: 'paragraph', content: 'Orders are not typically processed, packed, or dispatched on:' },
      {
        type: 'list',
        items: ['Sundays,', 'public holidays,', 'exceptional closure days,', 'periods of unusually high order volume.']
      },
      {
        type: 'paragraph',
        content:
          'If additional verification is needed for payment, address confirmation, fraud screening, or stock confirmation, processing may take longer.'
      }
    ]
  },
  {
    title: '2. Shipping Partners',
    blocks: [
      {
        type: 'paragraph',
        content:
          'We may use Shiprocket and/or third-party courier partners to fulfill and deliver orders. Carrier selection may vary by destination, serviceability, order value, product type, and operational conditions.'
      }
    ]
  },
  {
    title: '3. Delivery Timelines',
    blocks: [
      {
        type: 'paragraph',
        content:
          'Estimated delivery timelines shown on the site or at checkout are estimates only and are not guaranteed unless expressly stated otherwise.'
      },
      { type: 'paragraph', content: 'Delivery times may vary based on:' },
      {
        type: 'list',
        items: [
          'destination and serviceable pin code,',
          'courier operations,',
          'weather,',
          'transport disruptions,',
          'regional restrictions,',
          'inaccurate address details,',
          'customer availability to receive delivery,',
          'force majeure events,',
          'other circumstances beyond our control.'
        ]
      }
    ]
  },
  {
    title: '4. Shipping Charges',
    blocks: [
      {
        type: 'paragraph',
        content:
          'Shipping charges, handling charges, or related fees, if any, will be displayed at checkout or otherwise communicated before you complete your purchase.'
      },
      {
        type: 'paragraph',
        content:
          'We may offer promotional shipping terms from time to time, including free shipping above certain thresholds, subject to change without notice.'
      }
    ]
  },
  {
    title: '5. Address Accuracy',
    blocks: [
      { type: 'paragraph', content: 'You are responsible for providing accurate and complete shipping details, including:' },
      {
        type: 'list',
        items: ['recipient name,', 'phone number,', 'delivery address,', 'pin code,', 'landmark or access instructions where relevant.']
      },
      {
        type: 'paragraph',
        content:
          'We are not responsible for delays, failed deliveries, or additional charges resulting from incomplete, inaccurate, or outdated address information provided by you.'
      }
    ]
  },
  {
    title: '6. Shipment Tracking',
    blocks: [
      {
        type: 'paragraph',
        content:
          'Where tracking is available, we may provide shipment tracking details after dispatch. Tracking updates are generated by carrier systems and may not refresh in real time.'
      }
    ]
  },
  {
    title: '7. Multiple Shipments',
    blocks: [
      {
        type: 'paragraph',
        content:
          'An order may be shipped in one or more packages depending on stock location, packaging, carrier constraints, or operational decisions. Separate shipments may arrive at different times.'
      }
    ]
  },
  {
    title: '8. Delivery Attempts and Failed Delivery',
    blocks: [
      { type: 'paragraph', content: 'Courier partners may make a limited number of delivery attempts. If a delivery fails because:' },
      {
        type: 'list',
        items: [
          'the recipient is unavailable,',
          'the address is incorrect or incomplete,',
          'delivery is refused,',
          'the shipment remains unclaimed,',
          'the customer does not cooperate with delivery coordination,'
        ]
      },
      {
        type: 'paragraph',
        content:
          'the order may be returned to us, delayed, cancelled, or subject to re-shipping charges.'
      }
    ]
  },
  {
    title: '9. Delays Outside Our Control',
    blocks: [
      { type: 'paragraph', content: 'We are not liable for shipping or delivery delays caused by:' },
      {
        type: 'list',
        items: [
          'carrier disruptions,',
          'natural events,',
          'strikes,',
          'transport or customs issues,',
          'government actions,',
          'local restrictions,',
          'public emergencies,',
          'other force majeure events.'
        ]
      },
      {
        type: 'paragraph',
        content: 'We will make reasonable efforts to assist with tracking and coordination where possible.'
      }
    ]
  },
  {
    title: '10. Risk and Title',
    blocks: [
      {
        type: 'paragraph',
        content:
          'Unless otherwise required by applicable law, risk in the product passes to you upon delivery to the shipping address provided in the order.'
      }
    ]
  },
  {
    title: '11. Damaged or Tampered Packages',
    blocks: [
      {
        type: 'paragraph',
        content:
          'If the outer package appears visibly damaged, tampered, opened, or compromised at the time of delivery, you should:'
      },
      {
        type: 'list',
        items: ['refuse delivery where appropriate, or', 'record evidence at delivery and contact us as soon as possible.']
      },
      {
        type: 'paragraph',
        content:
          'If you accept such a package, please notify us within 48 hours of delivery with clear photos and your order details.'
      }
    ]
  },
  {
    title: '12. Serviceability',
    blocks: [
      {
        type: 'paragraph',
        content:
          'We reserve the right to decline, cancel, or restrict orders to locations that are not serviceable, operationally high-risk, restricted by courier availability, or otherwise unsuitable for shipment.'
      }
    ]
  },
  {
    title: '13. International Shipping',
    blocks: [
      {
        type: 'paragraph',
        content:
          'If international shipping is enabled in the future or expressly offered, additional customs duties, import taxes, brokerage charges, or destination-country fees may apply and shall generally be your responsibility unless stated otherwise at checkout.'
      }
    ]
  },
  {
    title: '14. Contact',
    blocks: [
      {
        type: 'paragraph',
        content: (
          <a href="mailto:studio@thevibestation.com" style={legalLinkStyle}>
            studio@thevibestation.com
          </a>
        )
      }
    ]
  }
];

export function ShippingPolicy() {
  usePageMeta();

  return (
    <LegalDocument
      title="Shipping Policy"
      lastUpdated="March 22, 2026"
      intro={['This Shipping Policy explains how Vibe Station processes, dispatches, and delivers orders placed through our website.']}
      sections={sections}
    />
  );
}

function usePageMeta() {
  useEffect(() => {
    const previousTitle = document.title;
    document.title = 'Shipping Policy';
    return () => {
      document.title = previousTitle;
    };
  }, []);

  useEffect(() => {
    let metaDescription = document.querySelector('meta[name="description"]');
    const hadMetaDescription = Boolean(metaDescription);

    if (!metaDescription) {
      metaDescription = document.createElement('meta');
      metaDescription.setAttribute('name', 'description');
      document.head.appendChild(metaDescription);
    }

    const previousDescription = metaDescription.getAttribute('content');
    metaDescription.setAttribute('content', META_DESCRIPTION);

    return () => {
      if (!metaDescription) {
        return;
      }

      if (hadMetaDescription) {
        if (previousDescription !== null) {
          metaDescription.setAttribute('content', previousDescription);
        }
      } else {
        metaDescription.remove();
      }
    };
  }, []);
}
